os: linux
dist: trusty
group: stable
language: python
python: 3.6
before_install:
  - sudo apt-get install tinyproxy
script:
  - |
    ./tinyproxy_exporter &
    PID=$!
    sleep 1
    kill $PID
    sudo rm /usr/share/tinyproxy/stats.html
    ./tinyproxy_exporter &
    PID=$!
    sleep 1
    kill -15 $PID
