os: linux
dist: trusty
group: stable
language: python
python: 3.6
before_install:
  - sudo apt-get install tinyproxy
script:
  - |
    ./tinyproxy_exporter &
    sleep 1
    if [ "$(pidof python3)" ]
    then
      kill "$(pidof python3)"
      sudo rm /usr/share/tinyproxy/stats.html
      sudo service tinyproxy restart
      ./tinyproxy_exporter &
      sleep 1
      if [ "$(pidof python3)" ]
      then
        kill "$(pidof python3)"
      else
        exit 1
      fi
    else
      exit 1
    fi
